; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Wed Feb 28 2018 12:35:56 GMT+1100 (AUS Eastern Summer Time)
; Wait for set temperatures to be reached
M116 P0